import { NgModule } from '@angular/core';
import {
  MatNativeDateModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatChipsModule,
  MatDividerModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  MatSliderModule,
  MatStepperModule,
  MatTableModule,
  MatGridListModule,
  MatToolbarModule,
  MatTooltipModule,
  MatTabsModule,
  MatDatepickerModule,
  MatSnackBarModule,
  MatCheckboxModule,
  MatRadioModule,
  MatSortModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatBottomSheetModule,
  MatAutocompleteModule,
  MatBadgeModule,
} from '@angular/material';

import {LayoutModule} from '@angular/cdk/layout';
import {TextFieldModule} from '@angular/cdk/text-field';

const materialModules: any[] = [
    MatNativeDateModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatChipsModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatStepperModule,
    MatTableModule,
    MatGridListModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTabsModule,
    MatDatepickerModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatRadioModule,
    MatSortModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatBottomSheetModule,
    MatAutocompleteModule,
    MatBadgeModule,
];

@NgModule({
  imports: [...materialModules],
  exports: [...materialModules],
})
export class AppMaterialModule { }
